### ISSUE TITLE
System.Exception: Block must have a unique code

### ISSUE THREAD

**Issue by WickedSchnitzel** [Farkoth/Ceramos#2]
```
[Server Error] Failed registering block ceramos:toolmold-raw-spatula: System.Exception: Block must have a unique code ('ceramos:toolmold-raw-spatula' is already in use)

   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 1600

   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 262

10.4.2023 12:09:41 [Server Error] Failed registering block ceramos:toolmold-burned-spatula: System.Exception: Block must have a unique code ('ceramos:toolmold-burned-spatula' is already in use)

   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 1600

   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 262
```

**Comment by WickedSchnitzel** [comment]
rc2 mp server

**Comment by Farkoth** [comment]
> rc2 mp server

Thanks for issue, i'll check it when back home

**Comment by Farkoth** [comment]
> rc2 mp server

It's must be fixed for now, but without BL compat. rc5
